idf_component_register(
    SRCS 
        "src/Layout.cpp"
        "src/LVAnimation.cpp"
        "src/LVAnimImg.cpp"
        "src/LVApplication.cpp"
        "src/LVArc.cpp"
        "src/LVBar.cpp"
        "src/LVButton.cpp"
        "src/LVCalendar.cpp"
        "src/LVCanvas.cpp"
        "src/LVChart.cpp"
        "src/LVCheckbox.cpp"
        "src/LVColor.cpp"
        "src/LVColorWheel.cpp"
        "src/LVDisplay.cpp"
        "src/LVDocument.cpp"
        "src/LVDropdown.cpp"
        "src/LVEvent.cpp"
        "src/LVImg.cpp"
        "src/LVIndev.cpp"
        "src/LVLabel.cpp"
        "src/LVList.cpp"
        "src/LVMenu.cpp"
        "src/LVMeter.cpp"
        "src/LVNavigator.cpp"
        "src/LVPanel.cpp"
        "src/LVRoller.cpp"
        "src/LVScreen.cpp"
        "src/LVSlider.cpp"
        "src/LVSpinbox.cpp"
        "src/LVSpinner.cpp"
        "src/LVStorage.cpp"
        "src/LVStyle.cpp"
        "src/LVSwitch.cpp"
        "src/LVTable.cpp"
        "src/LVTabView.cpp"
        "src/LVTextArea.cpp"
        "src/LVTileView.cpp"
        "src/LVTimer.cpp"
        "src/LVView.cpp"
        "src/LVWidget.cpp"
        "src/LVWindow.cpp"
        "src/ScreenManager.cpp"
        "src/VPITankGauge.cpp"
        "src/ElectricalPanel.cpp"
        "src/VPIHMIUI.cpp"
    INCLUDE_DIRS 
        "include"
    REQUIRES 
        lvgl__lvgl
        esp_lcd
        fatfs
        driver
        esp32_p4_function_ev_board
        font_thai
)
